kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    app: bitbucket
    app.kubernetes.io/component: bitbucket-server
    app.kubernetes.io/part-of: bitbucket
    app.kubernetes.io/managed-by: argocd
  name: bitbucket-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kube-data/bitbucket"
    type: Directory