apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitbucket
    app.kubernetes.io/component: bitbucket-server
    app.kubernetes.io/part-of: bitbucket
    app.kubernetes.io/managed-by: argocd
  name: bitbucket-server
spec:
  selector:
    app: bitbucket
  ports:
  - name: bitbucket-http
    port: 7990
  type: LoadBalancer