apiVersion: v1
kind: Service
metadata:
  labels:
    app: gogs
    app.kubernetes.io/component: gogs-server
    app.kubernetes.io/managed-by: argocd
  name: gogs-server
  namespace: gogs
spec:
  type: LoadBalancer
  selector:
    app: gogs-server
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000